//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class ChannelValues {
  Bools: boolean[];
  Bytes: string[];
  SignedIntegers16: number[];
  SignedIntegers32: number[];
  SignedIntegers64: number[];
  Doubles: number[];
  Strings: string[];

  constructor(args?: { Bools: boolean[]; Bytes: string[]; SignedIntegers16: number[]; SignedIntegers32: number[]; SignedIntegers64: number[]; Doubles: number[]; Strings: string[]; });
}

declare class Channel {
  Unit: string;
  Values: ChannelValues;
  DisplayIdentifier: string;
  Comment: string;
  LongIdentifier: string;

  constructor(args?: { Unit: string; Values: ChannelValues; DisplayIdentifier?: string; Comment?: string; LongIdentifier?: string; });
}

declare class ChannelGroup {
  TimeChannel: number[];
  DataChannels: { [k: string]: Channel; };
  DisplayIdentifier: string;
  Comment: string;
  LongIdentifier: string;

  constructor(args?: { TimeChannel: number[]; DataChannels: { [k: string]: Channel; }; DisplayIdentifier?: string; Comment?: string; LongIdentifier?: string; });
}

declare class MeasurementDataChunk {
  ChannelGroups: { [k: string]: ChannelGroup; };
  MeasurementSystemID: string;
  Comment: string;

  constructor(args?: { ChannelGroups: { [k: string]: ChannelGroup; }; MeasurementSystemID: string; Comment?: string; });
}
