//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
ThriftMessage = module.exports.ThriftMessage = function(args) {
  this.ProtocolFormat = null;
  this.Content = null;
  if (args) {
    if (args.ProtocolFormat !== undefined && args.ProtocolFormat !== null) {
      this.ProtocolFormat = args.ProtocolFormat;
    }
    if (args.Content !== undefined && args.Content !== null) {
      this.Content = args.Content;
    }
  }
};
ThriftMessage.prototype = {};
ThriftMessage.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.ProtocolFormat = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.Content = input.readBinary();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ThriftMessage.prototype.write = function(output) {
  output.writeStructBegin('ThriftMessage');
  if (this.ProtocolFormat !== null && this.ProtocolFormat !== undefined) {
    output.writeFieldBegin('ProtocolFormat', Thrift.Type.I32, 1);
    output.writeI32(this.ProtocolFormat);
    output.writeFieldEnd();
  }
  if (this.Content !== null && this.Content !== undefined) {
    output.writeFieldBegin('Content', Thrift.Type.STRING, 2);
    output.writeBinary(this.Content);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

