//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


/**
 * Ahh, now onto the cool part, defining a service. Services just need a name
 * and can optionally inherit from another service using the extends keyword.
 */
declare class ThriftMessageServiceClient {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  ProcessMessage(message: ThriftMessage): void;

  ProcessMessage(message: ThriftMessage, callback: Function): void;

  ProcessMessageAsync(message: ThriftMessage): void;

  ProcessMessageAsync(message: ThriftMessage, callback: Function): void;
}
