//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


/**
 * Represents a DSRC message.
 */
declare class ThriftDenmMessage {
  ProtocolFormat: number;
  Id: string;
  SenderId: string;
  Command: number;
  SenderType: number;
  ValueTimeSlice: ValuesTimeSlice;

  constructor(args?: { ProtocolFormat: number; Id: string; SenderId: string; Command: number; SenderType: number; ValueTimeSlice: ValuesTimeSlice; });
}
