//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


/**
 * Represents a Cam message.
 */
declare class ThriftCamMessage {
  ProtocolFormat: number;
  Id: string;
  SenderId: string;
  ValueTimeSlice: ValuesTimeSlice;

  constructor(args?: { ProtocolFormat: number; Id: string; SenderId: string; ValueTimeSlice: ValuesTimeSlice; });
}
