//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./MessageService_types');
//HELPER FUNCTIONS AND STRUCTURES

ThriftMessageService_ProcessMessage_args = function(args) {
  this.message = null;
  if (args) {
    if (args.message !== undefined && args.message !== null) {
      this.message = new ttypes.ThriftMessage(args.message);
    }
  }
};
ThriftMessageService_ProcessMessage_args.prototype = {};
ThriftMessageService_ProcessMessage_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.message = new ttypes.ThriftMessage();
        this.message.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ThriftMessageService_ProcessMessage_args.prototype.write = function(output) {
  output.writeStructBegin('ThriftMessageService_ProcessMessage_args');
  if (this.message !== null && this.message !== undefined) {
    output.writeFieldBegin('message', Thrift.Type.STRUCT, 1);
    this.message.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ThriftMessageService_ProcessMessage_result = function(args) {
};
ThriftMessageService_ProcessMessage_result.prototype = {};
ThriftMessageService_ProcessMessage_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ThriftMessageService_ProcessMessage_result.prototype.write = function(output) {
  output.writeStructBegin('ThriftMessageService_ProcessMessage_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ThriftMessageService_ProcessMessageAsync_args = function(args) {
  this.message = null;
  if (args) {
    if (args.message !== undefined && args.message !== null) {
      this.message = new ttypes.ThriftMessage(args.message);
    }
  }
};
ThriftMessageService_ProcessMessageAsync_args.prototype = {};
ThriftMessageService_ProcessMessageAsync_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.message = new ttypes.ThriftMessage();
        this.message.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ThriftMessageService_ProcessMessageAsync_args.prototype.write = function(output) {
  output.writeStructBegin('ThriftMessageService_ProcessMessageAsync_args');
  if (this.message !== null && this.message !== undefined) {
    output.writeFieldBegin('message', Thrift.Type.STRUCT, 1);
    this.message.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ThriftMessageService_ProcessMessageAsync_result = function(args) {
};
ThriftMessageService_ProcessMessageAsync_result.prototype = {};
ThriftMessageService_ProcessMessageAsync_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ThriftMessageService_ProcessMessageAsync_result.prototype.write = function(output) {
  output.writeStructBegin('ThriftMessageService_ProcessMessageAsync_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ThriftMessageServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ThriftMessageServiceClient.prototype = {};
ThriftMessageServiceClient.prototype.seqid = function() { return this._seqid; }
ThriftMessageServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
ThriftMessageServiceClient.prototype.ProcessMessage = function(message, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ProcessMessage(message);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ProcessMessage(message);
  }
};

ThriftMessageServiceClient.prototype.send_ProcessMessage = function(message) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ProcessMessage', Thrift.MessageType.CALL, this.seqid());
  var args = new ThriftMessageService_ProcessMessage_args();
  args.message = message;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ThriftMessageServiceClient.prototype.recv_ProcessMessage = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ThriftMessageService_ProcessMessage_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ThriftMessageServiceClient.prototype.ProcessMessageAsync = function(message, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ProcessMessageAsync(message);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ProcessMessageAsync(message);
  }
};

ThriftMessageServiceClient.prototype.send_ProcessMessageAsync = function(message) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ProcessMessageAsync', Thrift.MessageType.ONEWAY, this.seqid());
  var args = new ThriftMessageService_ProcessMessageAsync_args();
  args.message = message;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};
ThriftMessageServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ThriftMessageServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ThriftMessageServiceProcessor.prototype.process_ProcessMessage = function(seqid, input, output) {
  var args = new ThriftMessageService_ProcessMessage_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ProcessMessage.length === 1) {
    Q.fcall(this._handler.ProcessMessage, args.message)
      .then(function(result) {
        var result = new ThriftMessageService_ProcessMessage_result({success: result});
        output.writeMessageBegin("ProcessMessage", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ProcessMessage", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ProcessMessage(args.message, function (err, result) {
      if (err == null) {
        var result = new ThriftMessageService_ProcessMessage_result((err != null ? err : {success: result}));
        output.writeMessageBegin("ProcessMessage", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ProcessMessage", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

ThriftMessageServiceProcessor.prototype.process_ProcessMessageAsync = function(seqid, input, output) {
  var args = new ThriftMessageService_ProcessMessageAsync_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.ProcessMessageAsync(args.message)
}

