//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


/**
 * Represents an arbitary value within a ValueWithUnit
 */
declare class Value {
  Double: number;
  Bool: boolean;
  Integer: number;
  Long: number;
  String: string;

  constructor(args?: { Double: number; Bool: boolean; Integer: number; Long: number; String: string; });
}

/**
 * Represents an arbitary value with its corresponding unit as string.
 */
declare class ValueWithUnit {
  Value: Value;
  Unit: string;

  constructor(args?: { Value: Value; Unit: string; });
}

/**
 * A value time slice contains various numbers of values with units, identified by their name.
 * Additionally a timestamp when these values are recorded exists.
 */
declare class ValuesTimeSlice {
  Ticks: number;
  Values: { [k: string]: ValueWithUnit; };

  constructor(args?: { Ticks: number; Values: { [k: string]: ValueWithUnit; }; });
}
